# Generated by Django 6.0 on 2025-12-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="related",
        ),
        migrations.AlterField(
            model_name="media",
            name="source",
            field=models.CharField(blank=True),
        ),
    ]
