# Generated by Django 6.0 on 2025-12-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0002_remove_media_related_alter_media_source"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Media",
            new_name="File",
        ),
    ]
