# Generated by Django 6.0 on 2025-12-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0003_rename_media_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="nsfw",
        ),
        migrations.RemoveField(
            model_name="file",
            name="source",
        ),
        migrations.AlterField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="media/"),
        ),
    ]
