# Generated by Django 6.0 on 2025-12-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0004_remove_file_nsfw_remove_file_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="created",
        ),
        migrations.RemoveField(
            model_name="file",
            name="modified",
        ),
    ]
