# Generated by Django 6.0 on 2025-12-14 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0005_remove_file_created_remove_file_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(blank=True, upload_to="media/"),
        ),
    ]
