# Generated by Django 6.0 on 2025-12-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0006_file_created_file_modified_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="nsfw",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="source",
            field=models.CharField(blank=True),
        ),
    ]
