# Generated by Django 6.0 on 2025-12-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0007_file_nsfw_file_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="nsfw",
            field=models.BooleanField(default=False),
        ),
    ]
