# Generated by Django 6.0 on 2025-12-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0008_alter_file_nsfw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
