# Generated by Django 6.0 on 2025-12-17 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0009_alter_file_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="added_by",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="nsfw",
            field=models.BooleanField(default=False, verbose_name="NSFW"),
        ),
    ]
