# Generated by Django 6.0 on 2026-01-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0010_file_added_by_alter_file_nsfw"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
