# Generated by Django 6.0 on 2026-02-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0012_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nsfw",
            field=models.CharField(default="sfw"),
        ),
    ]
