# Generated by Django 6.0 on 2026-02-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0013_profile_nsfw"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="direction",
            field=models.CharField(default="desc"),
        ),
        migrations.AddField(
            model_name="profile",
            name="sort",
            field=models.CharField(default="modified"),
        ),
    ]
