# Generated by Django 6.0 on 2026-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0014_profile_direction_profile_sort"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="collections",
            field=models.ManyToManyField(to="stash.collection"),
        ),
    ]
