# Generated by Django 6.0 on 2026-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0015_collection_file_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="nsfw",
            field=models.BooleanField(default=False, verbose_name="NSFW"),
        ),
    ]
