# Generated by Django 6.0 on 2026-07-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stash", "0016_collection_nsfw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="collections",
            field=models.ManyToManyField(blank=True, to="stash.collection"),
        ),
    ]
